In [2]:
# Section:A
# Question 1

numbers = [10, 20, 30, 40, 50]

numbers.append(60)
print("Append:", numbers)

numbers.extend([70, 80])
print("Extend:", numbers)

numbers.insert(2, 25)
print("Insert:", numbers)

numbers.remove(40)
print("Remove:", numbers)

numbers.pop()
print("Pop:", numbers)

print("Index of 30:", numbers.index(30))

print("Count of 20:", numbers.count(20))

numbers.sort()
print("Sort:", numbers)

numbers.reverse()
print("Reverse:", numbers)

numbers.clear()
print("Clear:", numbers)

Append: [10, 20, 30, 40, 50, 60]
Extend: [10, 20, 30, 40, 50, 60, 70, 80]
Insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
Remove: [10, 20, 25, 30, 50, 60, 70, 80]
Pop: [10, 20, 25, 30, 50, 60, 70]
Index of 30: 3
Count of 20: 1
Sort: [10, 20, 25, 30, 50, 60, 70]
Reverse: [70, 60, 50, 30, 25, 20, 10]
Clear: []


In [5]:
# Question 2

students = ("Rahul", "Amit", "Priya")

print(students)

# students[1] = "Karan"

print("Tuples are immutable, so values cannot be changed.")

('Rahul', 'Amit', 'Priya')
Tuples are immutable, so values cannot be changed.


In [6]:
# Question 3

numbers_set = {1, 2, 3, 4, 4, 5, 5, 6}

print(numbers_set)

print("Sets do not allow duplicate values.")

{1, 2, 3, 4, 5, 6}
Sets do not allow duplicate values.


In [9]:
# Question 4

person = {
    "name": "Aryan",
    "age": 22,
    "city": "Ahmedabad"
}

person["name"] = "Aaryan"
person["email"] = "aryan@Gmail.com"

print(person)

{'name': 'Aaryan', 'age': 22, 'city': 'Ahmedabad', 'email': 'aryan@Gmail.com'}


In [10]:
# Question 5

age = 20

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote


In [11]:
# Question 6

marks = 82

if marks >= 90:
    print("Grade A")
elif marks >= 75:
    print("Grade B")
elif marks >= 50:
    print("Grade C")
else:
    print("Fail")

Grade B


In [12]:
# Question 7

number = -4

if number > 0:
    print("Positive Number")
    
    if number % 2 == 0:
        print("Even Number")
    else:
        print("Odd Number")

elif number == 0:
    print("Zero")

else:
    print("Negative Number")

Negative Number


In [13]:
# Section : B
# Question 8

import numpy as np

scalar = np.array(5)
print("Scalar:")
print(scalar)

array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])

print("2D Array:")
print(array_2d)

Scalar:
5
1D Array:
[1 2 3 4 5]
2D Array:
[[10 20 30]
 [40 50 60]]


In [14]:
# Question 9

import numpy as np

random_array = np.random.randint(0, 100, (4, 4))

print(random_array)

[[52 39 64 41]
 [59 14 79 94]
 [58 97 92 93]
 [88 97 10 60]]


In [15]:
# Question 10

import numpy as np
import pandas as pd

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

df = pd.DataFrame(array, columns=["A", "B", "C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [17]:
# Section : C
# Question 11

import pandas as pd
import numpy as np

data = {
    "Name": ["Amit", "Rahul", "Priya", "Sneha", "Karan",
             "Riya", "Vikas", "Neha", "Aman", "Pooja"],
    
    "Age": [21, 22, 20, 23, 24,
            22, 25, 21, 23, 24],
    
    "City": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar",
             "Ahmedabad", "Surat", "Rajkot", "Vadodara", "Bhavnagar"],
    
    "Salary": [25000, 30000, np.nan, 28000, 35000,
               32000, 40000, np.nan, 29000, 31000]
}

df = pd.DataFrame(data)

print(df)

print(df.info())

print(df.describe())

print(df[["Name", "City"]])

df = df.drop("City", axis=1)

mean_salary = df["Salary"].mean()

df["Salary"] = df["Salary"].fillna(mean_salary)

df = df.drop_duplicates()

print(df)

    Name  Age       City   Salary
0   Amit   21  Ahmedabad  25000.0
1  Rahul   22      Surat  30000.0
2  Priya   20   Vadodara      NaN
3  Sneha   23     Rajkot  28000.0
4  Karan   24  Bhavnagar  35000.0
5   Riya   22  Ahmedabad  32000.0
6  Vikas   25      Surat  40000.0
7   Neha   21     Rajkot      NaN
8   Aman   23   Vadodara  29000.0
9  Pooja   24  Bhavnagar  31000.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None
             Age        Salary
count  10.000000      8.000000
mean   22.500000  31250.000000
std     1.581139   4590.362575
min    20.000000  25000.000000
25%    21.250000  28750.000000
50%    22.500000  30500.000000
75%    23.7500